### ISSUE TITLE
Graphical Mode Bug

### ISSUE THREAD

**Issue by Pixelsuft** [copy/v86#628] opened 2022-03-05 11:46 UTC
Under Windows 95:
![image1](https://user-images.githubusercontent.com/68371847/156881122-a7b0bf2d-222b-4faa-a499-3d63dd653536.png)
![image2](https://user-images.githubusercontent.com/68371847/156881209-3a8e6ac0-1f58-4c81-87bc-6d42e3a8005e.png)
There is no that bug in windows 98 (maybe it only in svga mode?)

Also in windows95-boot/windows98-boot profile there is black screen when it is starting up (maybe when height > width?)

Before svga updates all worked good.

**Comment by Pixelsuft** [comment] 2022-03-07 01:15
win2k: Notepad cursor is not blinking while I'm not hovered on it

**Comment by copy** [comment] 2022-03-09 20:09
The windows 95/98 issues will be fixed soon.

> win2k: Notepad cursor is not blinking while I'm not hovered on it

I can't reproduce this. Maybe you're pressing alt and it opens the file menu? 

> same with resolution changing

Does this happen in any existing profile? Or could you upload the image for me?

**Comment by Pixelsuft** [comment] 2022-03-10 06:28
[Windows XP image](https://github.com/Pixelsuft/old-win-images/releases/download/img/copy_winxp_lite.rar)
.img original size is 4GB, so, on chrome you can get out of memory error

**Closed** 2022-03-11 07:22 UTC
Labels: bug
