### ISSUE TITLE
Difficulty loading .iso Linux distributions while using Virtual x86 on mobile browsers (iPad Pro)

### ISSUE THREAD

**Issue by SugarRayLua** [copy/v86#701] opened 2022-07-11 03:09 UTC
I'm able to easily select an .iso that I've downloaded from the internet (e.g. Tiny Core Linux or Damn Small Linux) and add it as a CD image to the startup menu of Virtual x86 and boot up that Linux distribution when using Virtual X86 on my Apple Mac Desktop browsers; however, when I try and attach the same .iso to the startup menu of Virtual x86 when using my mobile browsers on my iPad Pro (e.g. mobile Safari or mobile Chrome) the virtual machine indicates it starts to boot from the .iso and then seems to get stuck (loading doesn't progress after at least 10 minutes). Does anyone else have the same problem? I wasn't expecting any difference in booting from .iso images on my mobile device versus desktop as was expecting the browser interface and javascript/.wasm code would load the .iso images the same on both.

Fyi. 
Thanks!

**Comment by copy** [comment] 2022-07-11 05:23
I can't reproduce this issue, DSL boots fine from an iso file on my ipad.

**Comment by hello-smile6** [comment] 2022-07-11 06:26
> I can't reproduce this issue, DSL boots fine from an iso file on my ipad.

I think they're meaning that it takes a long time to load disk images.

**Comment by SugarRayLua** [comment] 2022-07-11 07:35
Thanks-- to clarify, the DSL demo works fine, but when I attempt to boot with non-demo DSL .iso that I downloaded from DSL district and attach it as a CD image it doesn't load using my iPad (or at least takes longer than 15 minutes that I waited) but does load fine when attach it as a CD image on my desktop Mac with Virtual x86.

**Comment by hello-smile6** [comment] 2022-07-11 23:43
@copy @SugarRayLua I noticed something similar today. When booting from CDROM, v86 takes a long time to start - long enough that it's like it's loading the entire CDROM into memory before starting.

**Comment by copy** [comment] 2023-08-31 22:29
The DSL image is indeed loaded completely. For other images, it depends on the guest OS and size of the file (see https://github.com/copy/v86/blob/eaae139/src/buffer.js#L772-L774).

I don't think this is CDROM-specific, and I don't think there's anything to fix here, so closing.

**Closed by copy** 2023-08-31 22:29 UTC
