### ISSUE TITLE
Pressing a key makes the mouse stop working

### ISSUE THREAD

**Issue by 1j01** [copy/v86#182] opened 2018-01-18 05:47 UTC
Permanently, as far as I can tell.

**Comment by BenNottelling** [comment] 2018-01-18 06:45
Dumb question incoming, but... modifier keys? Like alt or control or option (mac key)? Are those modifier keys?

**Comment by 1j01** [comment] 2018-01-18 07:10
Yes

**Comment by BenNottelling** [comment] 2018-01-18 07:14
Maybe a duplicate of #165?

**Comment by 1j01** [comment] 2018-01-18 07:17
I don't think so; the keyboard still works, and blurring the page doesn't make the mouse start working again.

**Comment by ErnWong** [comment] 2018-01-18 07:19
Potentially related, but also potentially not.

@1j01 Mind telling us what browser you're using, and what OSes these problems appeared in?

**Comment by ErnWong** [comment] 2018-01-18 07:20
Gottit, I can reproduce it in Windows 98 with Chrome, pressing alt freezes the mouse.

**Comment by 1j01** [comment] 2018-01-18 07:50
Yeah, Chrome and I tried several OSes, it seems to happen in any that have mouse support
Happens in Firefox as well...

And actually, I think it's just *any* key.

**Comment by BenNottelling** [comment] 2018-01-18 07:54
Can confirm it happens with any key, but only if you try to move the mouse while holding a key, otherwise it works fine

**Comment by 1j01** [comment] 2018-01-18 08:35
I wonder if it's interrupting the mouse packets with keyboard packets.

**Comment by ErnWong** [comment] 2018-01-20 00:00
I'm not too familiar with the PS/2 controller and how interrupts work, so I might be wrong and saying silly things.

I think the problem is because there's nothing to lower the mouse interrupt other than reading port 0x60, so when the mouse interrupt handler decides to skip the read, the interrupt is left in a permanently raised state.

I think this is what's happening:

1. We first hold down a key while waving the mouse like Harry Potter's wand.

2. Both the [keyboard adapter](https://github.com/copy/v86/blob/master/src/browser/keyboard.js) and the [mouse adapter](https://github.com/copy/v86/blob/master/src/browser/mouse.js) start sending data to the [PS/2 controller](https://github.com/copy/v86/blob/master/src/ps2.js).

3. At one point in time, the PS/2 controller [receives the keyboard data](https://github.com/copy/v86/blob/41b9d9935e4ce3fef15dc79353eda9601ab8ed10/src/ps2.js#L81-L84), and [puts the data](https://github.com/copy/v86/blob/41b9d9935e4ce3fef15dc79353eda9601ab8ed10/src/ps2.js#L193) into the keyboard buffer. The PS/2 controller then [raises the keyboard interrupt](https://github.com/copy/v86/blob/41b9d9935e4ce3fef15dc79353eda9601ab8ed10/src/ps2.js#L194) (IRQ1) to notify the OS that there are new keyboard data.

4. Similarly, at one point in time, the PS/2 controller [receives the mouse data](https://github.com/copy/v86/blob/41b9d9935e4ce3fef15dc79353eda9601ab8ed10/src/ps2.js#L86-L94), puts the packets into the [mouse buffer](https://github.com/copy/v86/blob/41b9d9935e4ce3fef15dc79353eda9601ab8ed10/src/ps2.js#L269-L271), and raises the [mouse interrupt](https://github.com/copy/v86/blob/41b9d9935e4ce3fef15dc79353eda9601ab8ed10/src/ps2.js#L275) (IRQ12) to notify the OS that there are new mouse packets.

5. At one point in time, the handler for the mouse interrupt from the operating system kicks in. It checks the [status port](https://github.com/copy/v86/blob/41b9d9935e4ce3fef15dc79353eda9601ab8ed10/src/ps2.js#L345-L363) to see if: (1) there are data in the output buffer to read (bit 0), and (2), the data in the output buffer is from the mouse (bit 5). In our implementation, we seem to be giving [priority to keyboard](https://github.com/copy/v86/blob/41b9d9935e4ce3fef15dc79353eda9601ab8ed10/src/ps2.js#L301-L304) packets before mouse packets, and because the keyboard buffer is not empty, the status port bit 5 is zero to indicate that the next byte to be read in port 0x60 will be keyboard data and not mouse data.
The interrupt handler finds out that the next byte to be read won't be the desired mouse data, so the handler does nothing else and returns. Note that the mouse interrupt did not get lowered because the handler did not read port 0x60 for the mouse packet.

6. After a while, the OS finally finishes handling all the keyboard packets, and the keyboard buffer gets cleared. Note: the mouse interrupt is still raised and has not been lowered yet.

7. More mouse packets are sent to the PS/2 controller, and the PS/2 controller yet again pushes more data into its mouse buffer, and tries raising the mouse interrupt. However, the previous mouse interrupt has not been lowered yet, and so the interrupt does not trigger the handler. At this point, you can see that the OS can no longer handle the mouse packets because the interrupts are not firing.

By lowering the interrupts explicitly before raising them, to ensure that there is always a rising edge, the problem seems to go away.

```diff
 PS2.prototype.mouse_irq = function()
 {
     if(this.command_register & 2)
     {
+        this.cpu.device_lower_irq(12);
         this.cpu.device_raise_irq(12);
     }
 };

 PS2.prototype.kbd_irq = function()
 {
     if(this.command_register & 1)
     {
+        this.cpu.device_lower_irq(1);
         this.cpu.device_raise_irq(1);
     }
 };
```

This seems to fix it for Windows 1, Windows 98, and ReactOS, but not quite for Kolibri OS... I wonder why.

**Closed** 2018-02-09 22:50 UTC
