### ISSUE TITLE
Add possibility to change CD/FDD image dynamically

### ISSUE THREAD

**Issue by seekerer** [copy/v86#291] opened 2019-06-03 15:27 UTC
Looks like that should have been already implemented, however, after going through issues/readme/docs I was unable to find out how could I change CD image dynamically.

Question is, is it possible to programmatically change CD/FDD image when the emulator is running?

So the idea is that I would like to install Windows 3.1 OS which is split into 6 FDD images. I would first need to load DOS, then set FDD to point to first floppy image, then start setup. During setup, I will want to switch from one floppy to another.

Is it possible somehow with current implementation?

**Comment by MailYouLater** [comment] 2019-06-26 23:01
Unless this feature's been introduced since I last played with v86, this isn't implemented yet.  I have personally done what you're trying to accomplish via a round-about method of saving the VM's state, altering the configuration, then reloading the previously saved state.  It's awkward, likely to cause issues if any caching is taking place (as from the VM's perspective the content just inexplicably changes without eject/insert occuring) but for installing DOS & Windows 3.1, it does work.  That said, it would be really nice if there was a 'proper' way to switch disks without restarting the VM.

**Comment by MailYouLater** [comment] 2019-06-27 17:48
Also, this is a dupe of #54.

**Comment by copy** [comment] 2019-08-02 16:58
Closing as duplicate of https://github.com/copy/v86/issues/54

**Closed by copy** 2019-08-02 16:58 UTC
