### ISSUE TITLE
Provide bootable image with 9p support

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#41] opened 2015-02-25 13:54 UTC
I want to use the 9p filesystem and inject files into it. To inject files, I need to get the emulator instance. The Arch Linux demo is, AFAIK, the only one that features 9p support, however, it only works with the production build, which uses the closure compiler, which means I cannot get the emulator instance (since I don't know how it was mangled).

I can also build the image myself, maybe you have recommendations on how to do this? I imagine that I only need to build a new kernel, since I can use the userland from ttylinux or the linux26 image.

**Comment by copy** [comment] 2015-02-25 14:25
The easiest way to do this is to build everything from scratch using [busybox](http://www.busybox.net/). This will include building userland, but it also handles making the boot loader and the disk image.

When you're done and the image is reasonably small, upload it somewhere and I'll make it available on the website.

**Comment by ysangkok** [comment] 2015-02-28 21:28
I found the kernel image in use in the Arch Linux demo: http://104.131.53.7:8086/arch/var/cache/pacman/pkg/linux-3.17.6-1-i686.pkg.tar.xz

I put it in on a file system and loaded it with GRUB (from a floppy). I used the flags from /proc/cmdline: `root=host9p rootfstype=9p rootflags=trans=virtio`. However, it is unable to mount the root file system. The backtrace is too large to be seen, but on kernels I compile myself (I tried 3.2 and 3.17.8), I'm probably getting the same problem: `no channels available`. Do you have any ideas why 9p is not working for me?

**Comment by copy** [comment] 2015-03-01 15:44
Do you want to boot from the 9p filesystem or just have a separate 9p partition?

In either case, you'll need to specify a JSON file with the filesystem infos (created using [this](https://github.com/copy/fs2json) script) and a path where the files are stored. See [filesystem.md](https://github.com/copy/v86/blob/master/docs/filesystem.md). If you want to boot from 9p, you put the root file system in there. 

The default front end only creates a 9p interface for the Archlinux profile at this point. If you're interested, I can make these specifiable via URL for custom profiles.

**Comment by ysangkok** [comment] 2015-03-01 19:22
I want to Linux to use the 9p filesystem as its root filesystem, this is why I tried specifying `root=host9p`.

I'm trying to mount the same filesystem, I just copied the JSON file to my local server (and correctly passed it to V86Starter). If the filesystem mounts, it may not load files due to CORS. But it's not even mounting yet. Once I get that working, I'll start playing with custom filesystems. I guess something is problematic with my boot process, this is what I'm trying to figure out. But I don't see how I'm doing it differently from you, though I must be doing some differently.

**Comment by copy** [comment] 2015-03-01 20:14
`no channels available` is and indicator that Linux *tries* to use 9p (via virtio, so that's correct so far), but there is no virtio channel. Can you

1. Check again that the emulator is initialised like [in this example](http://copy.sh/v86/docs/samples/arch.html) (it doesn't work online, just check the code).
2. Make sure the JSON file is correctly loaded.
3. Change `LOG_LEVEL` in `src/const.js` to `LOG_OTHER | LOG_IO | LOG_9P | LOG_VIRTIO | LOG_PCI` and attach the log here.

**Comment by ysangkok** [comment] 2015-03-01 21:22
Here is the log file: https://gist.github.com/ysangkok/c45fc83ca4abc08a2000

I can also make the kernel build and configuration available to you.

2015-03-01 21:14 GMT+01:00 Fabian <notifications@github.com>:

**Comment by copy** [comment] 2015-03-01 21:52
> I can also make the kernel build and configuration available to you.

Yes, please.

**Comment by ysangkok** [comment] 2015-03-01 22:22
here's the bzImage: https://hushfile.it/54f390f2c18a0#Q9LrJ0xpE757kL5ZfmN1wIuPQo_EUMly8t0vayHS

here's the kernel config: https://gist.github.com/ysangkok/10f9f2431356e5834b83

**Comment by copy** [comment] 2015-03-02 18:02
I built a CD image and can reproduce the problem. However, the same error is shown when booting from the CD in qemu with a virtio-9p filesystem.

I think the problem is that the kernel can't use a 9p filesystem as the first root. [This thread](http://unix.stackexchange.com/questions/90423/can-virtfs-9p-be-used-as-root-file-system) suggests that an initrd might be necessary to do the loading. Archlinux uses mkinitpcio for this purpose and in fact I had to make a small change to it to make booting from 9p work.

**Comment by ysangkok** [comment] 2015-03-11 01:20
Okay, I built the kernel with initramfs support (I can provide the kernel config, but the initramfs seems to work fine, so I don't think it's relevant). It is still not working though, I get the same "no channels available" error.

Here is my initramfs: https://hushfile.it/54ff977b3a875#VXoZlCVKsL6-rciu77T6s-jc9npaokT_taRWo6N-

It is really simple:
```
 % tree
.
├── busybox-i486
├── etc
│   └── fstab
├── init
├── proc
└── sys

3 directories, 3 files
```

The busybox-i486 is from http://www.busybox.net/downloads/binaries/latest/ . The contents of the fstab is:

```
proc            /proc      proc     defaults     0      0
devtmpfs        /dev       devtmpfs defaults     0      0
sysfs           /sys       sysfs    defaults     0      0
```

The contents of init (it's executable) is:
```
#!/busybox-i486 sh
/busybox-i486 mkdir -p bin usr/sbin usr/bin sbin
/busybox-i486 --install -s
mount -a
sh
```

After booting, I launch `mkdir /host9p; mount -t 9p host9p /host9p` and it fails.

**Comment by copy** [comment] 2015-03-11 04:42
Hrm, another idea: Do you have the following options set to `y` in the kernel?

- `CONFIG_VIRTIO`
- `CONFIG_VIRTIO_PCI`
- `CONFIG_NET_9P_VIRTIO`
- `CONFIG_NET_9P`
- `CONFIG_9P_FS`

**Comment by ysangkok** [comment] 2015-03-11 16:08
Yes, the only Virtio/9P options *NOT* set are:

```
# CONFIG_VIRTIO_BLK is not set
# CONFIG_VIRTIO_NET is not set
# CONFIG_VIRTIO_CONSOLE is not set
# CONFIG_VIRTIO_BALLOON is not set
# CONFIG_9P_FS_SECURITY is not set
```

These are set:

```
CONFIG_NET_9P=y
CONFIG_NET_9P_VIRTIO=y
CONFIG_NET_9P_DEBUG=y
CONFIG_VIRTIO=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_MMIO=y
CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y
CONFIG_9P_FS=y
CONFIG_9P_FSCACHE=y
CONFIG_9P_FS_POSIX_ACL=y
```

**Comment by copy** [comment] 2015-03-12 09:25
This works for me: `mkdir /host9p; mount -t 9p host9p /host9p`. 

Can you try it on http://copy.sh/v86/ (the online version is a bit newer than this repository)

**Comment by ysangkok** [comment] 2015-03-12 10:31
It mounts with the version on copy.sh/v86, but not with master! What is the difference?

**Comment by copy** [comment] 2015-03-12 10:42
Did you `git pull`? I pushed the last changes one hour ago.

There were no changes to 9p/virtio devices, but it could be the same problem as with network handling (#23), which was fixed.

**Comment by ysangkok** [comment] 2015-03-16 02:28
I finally made a pretty minimal image that boots from 9p: https://hushfile.it/55063f583b047#ki3pxjLddyeo5iM6tq1OJQJE6UPfGV7wAcYHcsQu

The build script: https://github.com/ysangkok/build-v86-9p-linux

**Comment by copy** [comment] 2015-03-18 15:42
Nice. Do you plan to build something specific with it?

I'll close this for now. Feel free to reopen if something breaks.

**Closed by copy** 2015-03-18 15:42 UTC

**Comment by ysangkok** [comment] 2015-03-25 12:29
@copy I need this cause the Arch Linux build is unstable. I want to test binaries that I build outside the emulator, in the emulator. I need a quick way to upload files to the emulator, the serial link is slow and the network interface is too slow too.

**Comment by proxy-m** [comment] 2021-06-17 11:12
It is possible to have **9p** without separate initrd only for Linux 4+ ?
[config_linux_4.txt](https://github.com/copy/v86/files/6669671/config_linux_4.txt)

**Comment by copy** [comment] 2021-06-17 19:16
@proxy-m I don't think it's possible, but please let us know if you find a way to do it.

**Comment by proxy-m** [comment] 2021-06-19 07:24
@copy , On Linux 4+ (4.1.4 and 4.19.182 tested) **9p** works with built-in initramfs (not initrd, similar). But on Linux 3 it does not.

Example for Linux 4+: https://theylied.info/speaker/index.html

**Comment by copy** [comment] 2021-06-19 14:48
@proxy-m Correct, the initramfs is only necessary when booting the kernel directly from the root filesystem. If you boot from an iso (`root=/dev/sr0` on the kernel command line) it's not necessary.

What I do think is impossible (but would like to be shown otherwise) is booting into the 9pfs directly (`root=host9p rootfstype=9p` on the kernel command line, without initrd).

**Comment by proxy-m** [comment] 2021-06-20 03:15
@copy , First off all: thank you.

1. Simple way. As you know you can use 9p with help of initrd/initramfs. You can always have minimal initramfs, built-in to linux kernel (4+).

2. Hard way is my ugly patch to `linux-src/net/9p/trans_virtio.c->p9_virtio_create`
```
/**
 * p9_virtio_create - allocate a new virtio channel
 * @client: client instance invoking this transport
 * @devname: string identifying the channel to connect to (unused)
 * @args: args passed from sys_mount() for per-transport options (unused)
 * ...
 */

static int
p9_virtio_create(struct p9_client *client, const char *devname, char *args)
{
	struct virtio_chan *chan;
	int ret = -ENOENT;
	int found = 0;

	mutex_lock(&virtio_9p_lock);
	devname = "host9p";  /* patch line 1 */
	strncpy(client->name, devname, sizeof(devname));  /* patch line 2 */
	client->proto_version = p9_proto_2000L;   /* patch line 3 */
	list_for_each_entry(chan, &virtio_chan_list, chan_list) {
		if (!strncmp(devname, chan->tag, chan->tag_len) &&
		    strlen(devname) == chan->tag_len) {
			if (!chan->inuse) {
				chan->inuse = true;
				found = 1;
				break;
			}
			ret = -EBUSY;
		}
	}
	mutex_unlock(&virtio_9p_lock);

	if (!found) {
		pr_err("no channels available\n");
		return ret;
	}

	client->trans = (void *)chan;
	client->status = Connected;
	chan->client = client;

	return 0;
}

```

Explanation: normally `client->name (devname)` is setted by sys_mount, it was unknown in case initial boot.

So now you can without initrd/initramfs:

`sudo qemu-system-i386 -m 256M -kernel ./output/images/bzImage -usb -fsdev local,id=host9p,path=./output/images/rootfs_for_9p/,security_model=none -device virtio-9p-pci,fsdev=host9p,mount_tag=host9p -nographic -append 'root=host9p ro rootfstype=9p rootflags=trans=virtio console=ttyS1'` # you can use ttyS0 to see boot log

bzImage (kernel) may be buggy, slow loading, I changed some other places, rebuild recommended.

md5 db629c76b2523568e1d558069aff4a3b  [bzImage.zip](https://github.com/copy/v86/files/6681664/bzImage.zip)
md5 41133b66f4140586450e679e6d24eba1 [rootfs_cpio.zip](https://github.com/copy/v86/files/6681668/rootfs_cpio.zip)

**Comment by proxy-m** [comment] 2021-06-20 09:23
*of all

**Comment by proxy-m** [comment] 2021-06-20 09:36
Bootable iso image, with help of the patch above. Only switchable rootfs_for_9p **9p** "folder" needed (e.g. from cpio above).

`sudo qemu-system-i386 -m 256M -cdrom ./output/images/rootfs.iso -usb -fsdev local,id=host9p,path=./output/images/rootfs_for_9p/,security_model=none -device virtio-9p-pci,fsdev=host9p,mount_tag=host9p`

md5 8446b34476d5e9ebc446fb7d3c31a164 [rootfs.iso.zip](https://github.com/copy/v86/files/6682016/rootfs.iso.zip)
[linux-config.txt](https://github.com/copy/v86/files/6682025/linux-config.txt)
[config.txt](https://github.com/copy/v86/files/6682027/config.txt)
