### ISSUE TITLE
Windows 95/98 Rebooting issue in Chrome

### ISSUE THREAD

**Issue by Chiccerino** [copy/v86#264] opened 2018-12-25 02:09 UTC
If you attempt to restart the operating system, on Win 98 you get stuck on [this](http://prntscr.com/lz72rb) screen and on win 95, you get stuck on [this](http://prntscr.com/lz72yz). Unfortunately you have to reload the entire page to fix the bug as the reset button doesn't exist on 95/98.

**Comment by liudonghua123** [comment] 2018-12-31 03:08
I have the similar problem, https://github.com/copy/v86/issues/250

**Comment by copy** [comment] 2019-01-18 18:31
Duplicate of #250.

> as the reset button doesn't exist on 95/98

Yeah, we throw away the state image to save memory space. I think that's the correct behaviour, even if it's slightly inconsistent.

**Closed by copy** 2019-01-18 18:31 UTC
