### ISSUE TITLE
Request: add ACPI support to the bios, or switch to one that supports it(whichever is easier)

### ISSUE THREAD

**Issue by FunnyDoggs** [copy/v86#1015] opened 2024-04-16 20:58 UTC
I would like this because as of right now without it can't load newer windows versions(such as 8.1)

**Comment by copy** [comment] 2024-04-16 21:10
Is acpi in the bios really the problem? qemu also uses seabios and (afaik) windows 8 works fine in it.

It's more likely that the problem is https://github.com/copy/v86/issues/845

**Comment by FunnyDoggs** [comment] 2024-04-16 21:48
I'll try the non-single language version as well. Is the NX bit support implemented? If it is required, I can't tell if it is working.

**Comment by FunnyDoggs** [comment] 2024-04-16 21:50
BTW, I just found out about this project today, and I(personally) think it is brilliant.

**Comment by FunnyDoggs** [comment] 2024-04-16 21:52
I do find it funny that while loading either version, you can't really read the trailing digits of the Bytes Read number=D

**Comment by FunnyDoggs** [comment] 2024-04-16 21:55
I just realized(on the single lang ver.[though probably like no difference]) it says, "...the firmware(BIOS) is not ACPI compatible."

**Comment by FunnyDoggs** [comment] 2024-04-16 21:59
Could it be because it is an ISO fresh from the download page on Microsoft's website?

Most likely not, but is a possibility.

**Comment by FunnyDoggs** [comment] 2024-04-16 22:07
The non-single language gives the same recovery screen.

**Comment by FunnyDoggs** [comment] 2024-04-16 22:09
I have now found the enable ACPI option.(embarrassed emoji would go here if I could find one).

**Comment by FunnyDoggs** [comment] 2024-04-16 22:13
Can you add a power button? I am now getting a infinite "Your PC needs to restart" error no matter how many times I reset.

**Comment by SuperMaxusa** [comment] 2024-04-16 22:18
> "Your PC needs to restart"

This error appears on Windows 8.x, when some instructions (mostly in our case NX-bit) doesn't supported by CPU, see #930

**Comment by FunnyDoggs** [comment] 2024-04-16 22:23
Can this be fixed somehow?

**Comment by FunnyDoggs** [comment] 2024-04-16 22:24
Like in the code files for the CPU or the BIOS(I don't know that much about the BIOS chip or the lower level stuff)

**Comment by FunnyDoggs** [comment] 2024-04-16 22:31
I am checking the JS console, and I get this error:
0043686a:0x84cca Uncaught RangeError: Maximum call stack size exceeded
    at 0043686a:0x84cca
    at 0043686a:0x8fe85
    at 0043686a:0x8f055
    at 0043686a:0x90050
    at 0043686a:0x850b6
    at 0043686a:0x8fe85
    at 0043686a:0x8f055
    at 0043686a:0x90050
    at 0043686a:0x850b6
    at 0043686a:0x8fe85

**Comment by FunnyDoggs** [comment] 2024-04-17 09:12
It only happens when the "Your pc needs to restart" stops repetitively printing itself.

**Comment by copy** [comment] 2024-04-17 17:42
Let's close this a duplicate of #845.

**Closed by copy** 2024-04-17 17:42 UTC
