### ISSUE TITLE
[ReactOS] Application Manager unable to install apps.

### ISSUE THREAD

**Issue by realwillgames** [copy/v86#802] opened 2023-02-10 23:50 UTC
Using the QtWeb browser is possible on ReactOS, however when attempting to download apps via the Application manager the app claims internet connection is non existent and will land on an assertion when trying to try again.

**Comment by spetterman66** [comment] 2023-02-11 07:34
just try again over and over, the download is resumable

**Comment by copy** [comment] 2023-08-26 22:12
I can reproduce this. No idea why it happens.

**Comment by BelleNottelling** [comment] 2023-08-26 22:23
IIRC, the ROS apps manager is particularly sensitive to the date/time being correct. When restoring from a save-state like the v86 interface does, the date/time is incorrect.

However, even if you can get it to load in and give you a list of apps, you can't really install anything anyways as the networking tends to lock up on long running transfers (regardless of how they are being performed, it seems to effect everything in the OS and not specifically the apps manager).

I do not know if that issue is in the ReactOS kernel, it's NE2K driver, how V86 emulates the NE2K, or because of a result of how the websocket proxy behaves. AFAIK Linux OS's don't have a similar issue in V86 so it very possibly could be an issue with ReactOS.

**Comment by SuperMaxusa** [comment] 2023-08-27 09:35
This is most likely due to an issue with SSL in ReactOS (since HTTPS sites via QTWeb are not loaded), and since the RAPPS database is loaded via HTTPS (https://github.com/reactos/reactos/commit/d564b4afc393fb0a98e61d9c23f689daf8bfbd90), the database update and installing apps may not work because of this.

**Comment by BelleNottelling** [comment] 2023-09-03 14:58
I think I've safely manage to eliminate the ReactOS NE2K driver as possible variable for this issue.
I tried this driver from the [realtek's website](https://www.realtek.com/en/component/zoo/category/rtl8029as-software) in ReactOS.
![image](https://github.com/copy/v86/assets/17304943/f782ab73-a3cf-4192-adfd-398dde04c79c)

While I was able to get it to install and connect without issue, I was also able to replicate what I previously described as the networking locking up. When attempting to allow the ReactOS Apps Manager to update the DB, it managed to download 32KB in over half an hour and at the end of when I gave up the network transfer was in the area of 10s or 100s of **BYTES** per second, which is significantly slower than what the proxy actually limits (`40980.0 bytes` going by the [source code](https://github.com/benjamincburns/websockproxy/blob/main/switchedrelay.py#L26C8-L26C15)).

## Speculation
As far as I can tell, it seems to get hung up on buffered data and will continue to handle it until completed, which completely hogs the networking until that buffered data is fully done.

An example of this can be seen in this GIF where I run a speed test. The download works fine & completed at which point the upload test is started and remains at nothing until the upload test is about half way through. During the first half, you can clearly see the bytes received is counting up quick quickly while zero bytes are being sent. It appears to be caught up on whatever data was still being received from the download portion of the test.
![Animation](https://github.com/copy/v86/assets/17304943/87ae566d-3e68-4b39-a1ed-a1f851d545d3)

I have also seen this the other way around, where the bytes sent will continue to count up for a significant time after cancelling the upload.

## Testing (Didn't work)
I tired to use the `tcpip.sys` file from Windows XP to see if that would effect the situation at all, however after swapping the file ReactOS no longer showed a network connection. In some cases ReactOS will work well with Windows components swapped in and in other cases it won't. It looks like this is a case where it doesn't work right, however it may work correctly with other files swapped. I've asked on the ReactOS mattermost to see if anyone knows whether or not `tcpip.sys` will work correctly in ReactOS, I'll follow up on this side of testing if I get more info (or think of something else).

If anyone wants to continue from this point, here are the steps to get to where I am now:
1. Extract the `TCPIP.sys` file from a Windows XP installation / ISO.
    a. For an ISO: Open it in your favorite tool (I used Z7ip, but AnyBurn is a great tool as well or you can mount the ISO in Windows)
    b. Pull `I386\TCPIP.SY_` from the ISO and place it somewhere you can easily find it
    c. Either open a CMD window in that directory (type `cmd` in the address bar in Explorer) or open a new CMD window and use `CD` to get to that directory.
    d. Expand the TCPIP file using `expand TCPIP.SY_ tcpip.sys`
    e. You can verify this worked by checking the file properties. They should be similar to this
![image](https://github.com/copy/v86/assets/17304943/f47084ea-76b1-46cd-a003-252ed37ab0b8)
2. Create an ISO with your `tcpip.sys` file (I used AnyBurn for this, it's great freeware)
3. Boot ReactOS into safe mode in Qemu with your ISO file attached as a disk.
4. Navigate to `C:\ReactOS\system32\drivers` and either `.old` or delete the `tcpip.sys` file that came with ReactOS.
5. Copy the new `tcpip.sys` that came from Windows XP to that folder
6. Reboot ReactOS
7. Make a frowny face because it didn't work :(

**Comment by BelleNottelling** [comment] 2023-09-05 11:59
So, it is seems to me that the issue is related either to the speed or the specific implementation of the proxy.
I tested the [node.js](https://github.com/krishenriksen/node-relay) version of the proxy and I was able to download 150MB in ReactOS from within v86 without any real issues:
![image](https://github.com/copy/v86/assets/17304943/06207c5a-5b94-4d22-b7c2-2b02f524f0e3)

When testing the older [python-based implementation](https://github.com/benjamincburns/websockproxy), I saw the same behavior that I previously described where the network transfer appeared to lock up.

It also doesn't appear to be a ReactOS specific issue either as I'm able to replicate similar (but not identical) networking issues in Haiku.

**Comment by BelleNottelling** [comment] 2023-09-07 16:59
@copy Any thoughts on this? (specifically the last message from me)
From what I'm seeing, this doesn't appear to be a v86 issue and is more related to the networking proxy itself

**Comment by SuperMaxusa** [comment] 2023-09-07 21:25
@BelleNottelling for the interest, I tried set RAPPS database on second VM with local HTTP server and App Manager can without problems download it
![rapps](https://github.com/copy/v86/assets/41739128/bcc53870-bc81-4fc7-9373-6559548fcd39)

So far, I also have some doubts about networking proxy, about other - no ideas yet :(

**Comment by copy** [comment] 2023-09-08 16:54
>  From what I'm seeing, this doesn't appear to be a v86 issue and is more related to the networking proxy itself

Correct, let's close this.

**Closed by copy** 2023-09-08 16:54 UTC
Labels: bug
