### ISSUE TITLE
Adding extra floppys after boot

### ISSUE THREAD

**Issue by abundant-ray** [copy/v86#413] opened 2021-03-06 04:05 UTC
is there any way to add more floppy disk images after boot? it would be a handy feature to have.
![image](https://user-images.githubusercontent.com/62371914/110194624-f62c5d80-7e9d-11eb-98bb-6c42106e47e7.png)
i know this will never be able to install but i want to see how far i can get. (this is as far as i can so far as you cant load more images)

**Comment by copy** [comment] 2021-03-06 04:09
Duplicate of https://github.com/copy/v86/issues/54

**Closed by copy** 2021-03-06 04:09 UTC
