### ISSUE TITLE
Mounting CDROM ISO after loading emulator???

### ISSUE THREAD

**Issue by evonox** [copy/v86#1086] opened 2024-07-20 20:55 UTC
Is it possible to mount CDROM ISO image from the outside using JavaScript? I am reading the source code, searching documentation and cannot find a way how to handle it.

**Comment by SuperMaxusa** [comment] 2024-07-20 21:29
See #900

**Comment by copy** [comment] 2024-07-22 21:42
Currently not supported, let's close this as a duplicate of #54.

**Closed by copy** 2024-07-22 21:42 UTC
