### ISSUE TITLE
[windows2000] Error code: SIGTRAP

### ISSUE THREAD

**Issue by kenorb** [copy/v86#556] opened 2021-11-13 14:26 UTC
I've run https://copy.sh/v86/?profile=windows2000

The following snap/crash happens in Chrome browser (version 95.0.4638.69, 64-bit):

> Error code: SIGTRAP

Usually it happens when clicking on 'My Computer', then opening 'Local Drive (C:)' and within 1 second before or after icons are showed up. It doesn't happen when _DevTools_ are opened.

**Comment by copy** [comment] 2021-11-13 18:21
I can reproduce this. I also reverted to an older version of v86 (from January this year) and it had the same issue.

When the crash happens chromium writes to stdout:

```
[1113/130654.523827:ERROR:ptracer.cc(422)] ptrace: No such process (3)
[1113/130654.523843:ERROR:ptracer.cc(446)] Unexpected registers size 0 != 216
[1113/130654.523846:WARNING:process_reader_linux.cc(378)] Couldn't initialize main thread.
[1113/130701.979100:ERROR:scoped_ptrace_attach.cc(37)] process not stopped
[1113/130701.979123:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979131:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979133:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979135:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979137:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979140:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979142:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979144:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979146:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979148:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979150:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979152:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979154:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979156:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979160:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979164:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979167:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979172:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979176:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979180:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130701.979184:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130702.406928:ERROR:scoped_ptrace_attach.cc(37)] process not stopped
[1113/130702.406947:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130702.406954:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130702.406956:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130702.406958:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130702.406961:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[1113/130702.406972:ERROR:file_io_posix.cc(144)] open /proc/333/auxv: Permission denied (13)
[1113/130702.406979:ERROR:process_memory.cc(41)] short read
[1113/130702.406982:ERROR:process_snapshot_linux.cc(75)] Couldn't read exception info
[1113/130702.407203:ERROR:scoped_ptrace_attach.cc(45)] ptrace: No such process (3)
[1113/130702.407253:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[1113/130702.407303:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[1113/130702.407322:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[1113/130702.407343:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[1113/130702.407370:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[2:2:1113/130751.760924:ERROR:zygote_communication_linux.cc(276)] Failed to send GetTerminationStatus message to zygote
```

**Comment by copy** [comment] 2021-11-13 18:24
Setting [`MAX_PAGES`](https://github.com/copy/v86/blob/d155439329875109a1b00bfbb557f32c550aade7/src/rust/jit.rs#L327) to 1 seems to fix the issue, so it's probably related to some of the existing issues chromium has with big wasm modules.

**Comment by copy** [comment] 2021-11-17 22:59
For reference, here's the corresponding issue on the chromium bugtracker: https://bugs.chromium.org/p/v8/issues/detail?id=11020

**Comment by copy** [comment] 2024-04-23 10:32
Cannot reproduce any more, likely has been fixed in chromium.

**Closed by copy** 2024-04-23 10:32 UTC
Labels: bug
