### ISSUE TITLE
No keyboard input on Arch

### ISSUE THREAD

**Issue by oakes** [copy/v86#146] opened 2017-04-16 01:04 UTC
I successfully booted my own Arch disk image, but it does not accept any keyboard input. I also noticed it boots at 640x480 resolution, unlike your version. Is there something I need to add to the configuration? I already added `atkbd` to `MODULES` in `/etc/mkinitcpio.conf` but that appears to have no effect.

I am able to use the arrow keys during the GRUB boot screen, so it appears to only be a problem once Arch has booted. I'm using Archlinux version 2017.02.01, the last one to include 32-bit support. Any guidance would be very appreciated.

**Comment by oakes** [comment] 2017-04-17 14:40
Haven't figured it out yet, but since this is only an issue with my Arch image and not yours, I'll close and try to figure it out.

**Comment by copy** [comment] 2017-04-17 15:43
It's a problem on newer kernels, not specifically with your disk image.

**Comment by copy** [comment] 2017-04-28 00:03
The problem is what was mentioned in https://www.archlinux.org/news/linux-313-warning-ps2-keyboard-support-is-now-modular/: Linux doesn't check the PS2 ports directly any more, it searches for a [PNP](https://en.wikipedia.org/wiki/Legacy_Plug_and_Play) description for the device. I'm reluctant to implement PNP, since it's such an old and useless standard.

The workaround in the announcement doesn't work any more, in newer kernels it is necessary to also add `i8042` to the `MODULES` in `/etc/mkinitcpio.conf`, i.e.:

```
MODULES="atkbd i8042"
```

Using this, keyboard works again in v86. I'll close this and document it.

**Closed by copy** 2017-04-28 00:03 UTC
