### ISSUE TITLE
Loading large statefile fails?

### ISSUE THREAD

**Issue by nmcain** [copy/v86#330] opened 2020-03-26 03:23 UTC
I have compiled a custom buildroot Linux system that takes a while to boot, so I decided to use a statefile with the already booted system running x. It performs very well from the website when I load the state by hand, but I need it to load from my embedded page. When I try to load the state using initial_state, it loads the 256mb (240MB RAM, 16MB VRAM)statefile and the system ISO (as evidenced by the chrome network inspector tab), but never starts emulating. Am I doing something wrong? I tried having the iso load asynchronously but it still fails to boot.

**Comment by copy** [comment] 2020-03-29 16:38
Hard to say. Some things to try:

- Maybe you're missing `{ autostart: true }`?
- Any errors in the console?
- Are you passing the same settings as in the original instance?
- Is the emulator running (high cpu usage) or paused?
- If you press the pause button in the sources tab in Chromium's dev tools, does it stop somewhere in v86's code?
- What's the console output if you change DEBUG=false to DEBUG=true in the [Makefile](https://github.com/copy/v86/blob/9c018e3d3af4b7be4bbd6cbb8cf9733020429293/Makefile#L120)?

**Comment by nmcain** [comment] 2020-03-29 19:08
I have the autostart set to true, and the only console output is "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", even after passing the debug flag in the makefile. The emulator does not start at all, it loads the black box and stops. It pauses at : 

`var G = function() {
            for (var a = 0; a < B; a++)
                v[a] && (A.text_update_row(a),
                v[a] = 0);
            this.timer()
        }
        .bind(this)
          , F = function() {
            this.bus.send("screen-fill-buffer");
            this.timer()
        }`

**Comment by copy** [comment] 2020-05-28 00:04
There must be *some* debug output if you enable debugging and have autostart set. The first debug message usually is `mmap_register`, which is called unconditionally when the container is started. Do you have a minimal example to reproduce?

**Comment by copy** [comment] 2021-01-04 07:56
Closing since we can't reproduce.

**Closed by copy** 2021-01-04 07:56 UTC

**Comment by HunterBoy344** [comment] 2024-07-22 03:07
Having this same issue except with a large 3GB HDD image.
