### ISSUE TITLE
V86 doesn't load on iOS 9.3.5 (iPhone 4S)

### ISSUE THREAD

**Issue by niansa** [copy/v86#226] opened 2018-08-28 19:53 UTC
The OS List does load, but whenever i Start any OS there is only the footer on the screen, nothing Else.

**Comment by BenNottelling** [comment] 2018-08-28 19:59
What browser? (And version)

**Comment by nkrapivin** [comment] 2018-08-30 02:17
Same on PS4 browser and Tizen Smart TV browser

**Comment by niansa** [comment] 2018-08-30 17:14
Browser is Safari. Same problem on Android 4.0.4 webview

**Comment by niansa** [comment] 2018-09-04 14:14
Firefox and Chrome are incompatible.

**Comment by BenNottelling** [comment] 2018-09-16 23:42
Oh. Either way, I think that it'll be too old for v86.

**Comment by ElCresh** [comment] 2018-09-16 23:46
I've tried on an iPhone 6S with iOS 11.4.1 and works fine so I can confirm that is most likely an older (and so incompatible) versione of Safari the issue. Maybe also PS4 browse use some kind of olde WebKit implementation (I can't check right now). For Tizen I have no way to check unfortunatly.

**Comment by copy** [comment] 2019-01-18 18:44
I'm gonna close this as we're extremely unlikely to support old browsers.

**Closed by copy** 2019-01-18 18:44 UTC

**Comment by ItsTheAwesomestChannel85** [comment] 2019-05-02 00:17
I have an Amazon Fire 7, and it works, there just is no way to tell what you're doing because of the following things:

1. Everything is impossible to see because it all is 1px. in height, width has no change.
2.Everytime I tap, the keyboard comes up.

The same happens on [Charlie Somerville](charlie.bz), and FYI, the browser on Amazon Fires is called "Silk Browser".
