### ISSUE TITLE
v86 won't build on Ubuntu WSL2

### ISSUE THREAD

**Issue by TCFFan123** [copy/v86#811] opened 2023-03-08 00:10 UTC
Here's the log:
```
mkdir -p build/
BLOCK_SIZE=K ls -l build/v86-debug.wasm
ls: cannot access 'build/v86-debug.wasm': No such file or directory
make: [Makefile:182: build/v86-debug.wasm] Error 2 (ignored)
cargo rustc --target wasm32-unknown-unknown -- -C linker=tools/rust-lld-wrapper -C link-args="--import-table --global-base=4096 " -C link-args="build/softfloat.o" -C link-args="build/zstddeclib.o" --verbose -C target-feature=+bulk-memory
**Segmentation fault**
make: *** [Makefile:183: build/v86-debug.wasm] Error 139
```
I believe maybe this is a issue with WSL.
Some host system info:
Microsoft Windows [Version 10.0.22000.1455]
CPU is Intel(R) Core(TM) i3-10110U CPU @2.10GHz

**Comment by copy** [comment] 2023-03-08 11:44
Can you build rust applications at all? (e.g. `cargo init && cargo rustc`)?

**Comment by TCFFan123** [comment] 2023-03-09 02:18
I got ```Segmentation fault```.

**Comment by copy** [comment] 2023-03-09 10:52
It looks like an issue with your wsl or rust install then. I'd try wiping it, or perhaps trying with a different distribution or installing a different version of rust. However, since the problem is not v86-specific, I'll close this issue.

**Closed by copy** 2023-03-09 10:52 UTC
