### ISSUE TITLE
Links on copy.sh doesn't work anymore

### ISSUE THREAD

**Issue by jonasandero** [copy/v86#124] opened 2016-12-27 13:51 UTC
For example, https://copy.sh/v86/?profile=linux3 says 

> Loading //i.copy.sh/images/linux3.iso failed. Check your connection and reload the page to try again.

**Comment by copy** [comment] 2016-12-27 20:45
I can't reproduce the problem, do you have access to this file? https://i.copy.sh/images/linux3.iso

**Comment by copy** [comment] 2017-01-18 01:05
Closed as can't reproduce.

**Closed by copy** 2017-01-18 01:05 UTC
