### ISSUE TITLE
no internet in windows xp

### ISSUE THREAD

**Issue by 100tomer** [copy/v86#1131] opened 2024-08-21 17:24 UTC
Hi! I followed the instruction in the windows-xp.md file and it seems there is not network inside the windows xp. Any help will be much appreciated

**Comment by SuperMaxusa** [comment] 2024-08-21 20:18
Does networking work on QEMU with `-nic user,model=ne2k_pci`?

**Comment by FunnyCorgi** [comment] 2024-08-21 23:55
@SuperMaxusa @100tomer I just got my winxp instance setup, I will test this theory.

**Comment by FunnyCorgi** [comment] 2024-08-22 00:42
qemu networking does not work with this option.

**Comment by FunnyCorgi** [comment] 2024-08-22 00:42
I don't know how to get winxp internet working.

**Comment by SuperMaxusa** [comment] 2024-08-22 15:08
Works for me on SP2-3 in QEMU and v86. 
Can you check Device Manager (Win + R -> devmgmt.msc)? There should be a device "Realtek RTL8029(AS)" as in the screenshot, if not - try to add with **Add Hardware Wizard** in the Control Panel or install this driver: https://github.com/copy/v86/issues/392#issuecomment-1402659862

![ne2k-wxp](https://github.com/user-attachments/assets/d8ced316-f612-4d3f-b518-1c756c89a40c)

**Comment by FunnyCorgi** [comment] 2024-08-22 15:31
So your saying I need to use this driver as mentioned in the post?

**Comment by FunnyCorgi** [comment] 2024-08-22 15:34
@SuperMaxusa  but the realtek thing shows up in both qemu and v86(wait actually checking right now will report back in about five minutes)

**Comment by FunnyCorgi** [comment] 2024-08-22 15:35
Also, i only made an administrator account, and not a user account. Should that matter?

**Comment by SuperMaxusa** [comment] 2024-08-22 15:38
> So your saying I need to use this driver as mentioned in the post?

Driver for this network card is out-of-box in Windows XP, I leave a driver for 2000, if your system didn't find/install it. 

> Also, i only made an administrator account, and not a user account. Should that matter?

Likely no, I have tested with local and Administrator accounts too.

**Comment by FunnyCorgi** [comment] 2024-08-22 15:40
It detects it(I checked this morning in v86) but it is unable to ping google because DNS failed. DOes this mean I should install the driver?

**Comment by SuperMaxusa** [comment] 2024-08-22 15:43
> but it is unable to ping google because DNS failed.

Is it on v86 or QEMU? If on v86, are you using the default proxy or fetch-based networking?

**Comment by FunnyCorgi** [comment] 2024-08-22 15:44
Do I need debug.html for that? because I am using the wss:// relay proxy

**Comment by FunnyCorgi** [comment] 2024-08-22 15:47
Confirmed, it shows up. Here is my v86 screenshot of the device manager:
![download](https://github.com/user-attachments/assets/3a675b1c-e808-42e6-ad36-6f41378d550f)

**Comment by FunnyCorgi** [comment] 2024-08-22 15:47
Other devices are there because I canceled the install requests for those and haven't rebooted yet.

**Comment by FunnyCorgi** [comment] 2024-08-22 15:54
I will try running it in qemu now and see if I get the same result.

**Comment by SuperMaxusa** [comment] 2024-08-22 15:55
> but it is unable to ping google because DNS failed.

Is `ping 8.8.8.8` works for you?

> Do I need debug.html for that?

No, not needed.

Also check `ipconfig /all`, if networking settigns are correct, this should give IP address of your VM and DNS server `10.5.0.1` (on v86 with default proxy).

**Comment by FunnyCorgi** [comment] 2024-08-22 15:59
ok will try that.

**Comment by FunnyCorgi** [comment] 2024-08-22 16:02
Got this:
![download](https://github.com/user-attachments/assets/537d53d9-854b-4b32-8f07-6f81113698d5)

**Comment by FunnyCorgi** [comment] 2024-08-22 16:03
wait here is the ipconfig command output hold on

**Comment by FunnyCorgi** [comment] 2024-08-22 16:04
![download](https://github.com/user-attachments/assets/4e84a410-4b68-4ccc-9092-313dff4775e7)

**Comment by FunnyCorgi** [comment] 2024-08-22 16:05
Should I try renewing them?

**Comment by SuperMaxusa** [comment] 2024-08-22 16:09
Yes, try `ipconfig /release *` and `ipconfig /renew *`, seems that your system doesn't get an IP address from DHCP server. Have you had any errors in the browser console?

**Comment by FunnyCorgi** [comment] 2024-08-22 16:10
I can't really check for errors because I am using a managed system right now, but I will check on a vm.

**Comment by 100tomer** [comment] 2024-08-22 16:28
For me u got ping working but internet explorer isn't working. I'll check the driver name

**Comment by 100tomer** [comment] 2024-08-22 16:36
I see the Realltek drive in device managment and also ping is fully working. my dsn servers, dhcp server and gateway is 10.5.0.1. 
It seems that something is just broken with internet explorer

**Comment by 100tomer** [comment] 2024-08-22 16:40
I just noticed you have mozila browser, did it come with the xp? because I'm stuck with Explorer that does not work, and can't figure out how to download anything without it working

**Comment by SuperMaxusa** [comment] 2024-08-22 16:40
> It seems that something is just broken with internet explorer

Do sites like google.com, frogfind.com, example.com and theoldnet.com work in your Internet Explorer?

**Comment by 100tomer** [comment] 2024-08-22 16:46
> > It seems that something is just broken with internet explorer
> 
> Do sites like google.com, frogfind.com, example.com and theoldnet.com work in your Internet Explorer?
> 
> > I just noticed you have mozila browser, did it come with the xp?
> 
> No, I downloaded my Firefox 29 (for Windows XP SP2+) from https://ftp.mozilla.org/pub/firefox/releases/ on my host machine, then created ISO with the installer and mount this image to QEMU.

So all the websites you mentions are not working via internet explorer but I can ping them.

And about mozila sounds cool but I don't know how to do this. Is it the solution ? or is the internet explorer suppost to work?

**Comment by SuperMaxusa** [comment] 2024-08-22 17:08
> So all the websites you mentions are not working via internet explorer but I can ping them.

On QEMU too?

> And about mozila sounds cool but I don't know how to do this. Is it the solution ?

Not sure if ftp.mozilla.org can be opened with IE but worth checking. Also here is easiest ways for transfer files from host to guest OS in QEMU: https://wiki.archlinux.org/title/QEMU#QEMU's_built-in_SMB_server, https://www.qemu.org/docs/master/system/qemu-block-drivers.html#virtual-fat-disk-images

**Comment by 100tomer** [comment] 2024-08-22 17:12
I don't know how to use qemu yet, so I just checking it out. I managed to run the same windows xp image using qemu cli tool locally on my computer. Internet explorer is not working their too, I tried to mount the firefox.exe
 as a cd drive using the UI but windows says it's not formatted or somthing

**Comment by FunnyCorgi** [comment] 2024-08-22 17:26
use ImgBurn for the image(if using wine, use windows xp in winecfg) or here is my image:
https://drive.google.com/file/d/1Wn7ziWeMoH9cqJo7GFcRX8o0kbd11we3/view?usp=sharing
Use this command:
qemu-system-x86_64 -smp 2 -m 2G -drive file=winxp.img,format=raw -cdrom firefoxsetup\ foldercdrom.iso

**Comment by FunnyCorgi** [comment] 2024-08-22 17:27
also @SuperMaxusa there were no errors in the console with ipconfig, forgot to try ping, but doing now, and I still didn't connect and get an IP or dns

**Comment by 100tomer** [comment] 2024-08-22 17:29
> use ImgBurn for the image(if using wine, use windows xp in winecfg) or here is my image: https://drive.google.com/file/d/1Wn7ziWeMoH9cqJo7GFcRX8o0kbd11we3/view?usp=sharing Use this command: qemu-system-x86_64 -smp 2 -m 2G -drive file=winxp.img,format=raw -cdrom firefoxsetup\ foldercdrom.iso

Cool thanks now I can see the installation in windows xp, I'll update you if it's working. 
How do I save it to .img file after I install the firefox?

**Comment by FunnyCorgi** [comment] 2024-08-22 17:32
If using v86, you have to save the state of the machine.

**Comment by FunnyCorgi** [comment] 2024-08-22 17:33
@SuperMaxusa it still gives destination host unreachable

**Comment by 100tomer** [comment] 2024-08-22 17:34
> If using v86, you have to save the state of the machine.

Yeah I meant how to save it after I ran it and installed the firefox. Is it make sense the firefox isn't working on windows xp that runs locally using the qemu as well? 
I used qemu-system-x86_64 -smp 2 -m 2G -drive file=winxp.img,format=raw -cdrom firefoxsetup\ foldercdrom.iso command to run it

**Comment by FunnyCorgi** [comment] 2024-08-22 17:34
then the image it is saved in is that winxp.img. QEMU always saves changes to whatever drive images it uses.

**Comment by 100tomer** [comment] 2024-08-22 17:35
> then the image it is saved in is that winxp.img. QEMU always saves changes to whatever drive images it uses.

Oh I didn't know this

**Comment by FunnyCorgi** [comment] 2024-08-22 17:36
The firefox takes a long time to launch, just let it load.

**Comment by 100tomer** [comment] 2024-08-22 17:38
> The firefox takes a long time to launch, just let it load.

it says "server not found" does it still loading the website? also is there a imgBurn alternative for mac to create iso from a file?

**Comment by FunnyCorgi** [comment] 2024-08-22 17:44
> it says "server not found" does it still loading the website?
That is the DNS not resolving the website IP, it is part of the internet not working that we are working on fixing in this issue
>also is there a imgBurn alternative for mac to create iso from a file?
i don't think so? try wine with windows xp as the windows version in applications section after running imgburn installer(change it after running the installer), and then launch it, also make sure to use the files/folders to disc image option in the imgburn menu

**Comment by FunnyCorgi** [comment] 2024-08-22 17:45
of course, make sure to install the winehq package in macos

**Comment by FunnyCorgi** [comment] 2024-08-22 17:46
i believe https://www.embird.net/sw/embird/tutorial/wine/wine.htm should help for macos

**Comment by FunnyCorgi** [comment] 2024-08-22 17:47
to change winecfg run the command `wine winecfg`

**Comment by SuperMaxusa** [comment] 2024-08-22 17:47
> it still gives destination host unreachable

Is `nslookup example.com` also gives errors?

> also is there a imgBurn alternative for mac to create iso from a file?

See https://www.petenetlive.com/KB/Article/0001554

**Comment by FunnyCorgi** [comment] 2024-08-22 17:48
> > it still gives destination host unreachable
> 
> Is `nslookup example.com` also gives errors?

I'll try that

**Comment by FunnyCorgi** [comment] 2024-08-22 17:58
`nslookup` didn't work.
![download](https://github.com/user-attachments/assets/804a6ef0-b3ca-4eff-b896-d4490ed5d87d)

**Comment by FunnyCorgi** [comment] 2024-08-22 18:55
@SuperMaxusa what should me and @100tomer try next to fix this?

**Comment by SuperMaxusa** [comment] 2024-08-22 18:58
Let's summarize what we have at the moment:

 About not working **DNS** or/and **DHCP**: 
 + Check that you can to connect to default websockrelay: https://github.com/copy/v86/issues/954
 + If you can open a page, close tabs with v86, go to https://copy.sh/v86 and [clean cache](https://www.locksmith.guide/tutorials/more/how-to-clear-cache-for-a-single-website).
 + (in XP) Go to _Control Panel_ -> _Network Connection_ -> right-click on active connection -> _Properties_ -> select _Internet Protocol (TCP/IP)_ -> _Properties_. 
"Obtain an IP address automatically" (by default) should be set. 
 + If you get an IP address in `ipconfig /all` (eg. not `0.0.0.0`), but `nslookup` doesn't work and `ping 8.8.8.8` works properly, you can set "Use the following DNS server" and type:
 > Preferred DNS server: `8.8.8.8`
 > Alternative DNS server: `8.8.4.4`
 
 It set a Google DNS if provided by relay DNS not resolving for you.
 
![xp-dns](https://github.com/user-attachments/assets/ce510f01-e072-47a8-b78c-6973fc38eb66)

 About not working sites in IE: 
 - I got working some HTTP websites (+ also ftp.mozilla.org works) on Internet Explorer 6.0. 
 On QEMU it also should work, all settings in IE set by default (I opened it for the first time in this system).
 
![xp-web](https://github.com/user-attachments/assets/700f359b-0af6-4091-8545-cdb72a85984d)

**Comment by FunnyCorgi** [comment] 2024-08-23 00:14
@SuperMaxusa What do I do if it isn't showing up in network connections as a connection, but it registers it as a device without a non-built-in driver in the device manager and it shows up in `ipconfig /all` _and_ device manager says it is working properly.

**Comment by FunnyCorgi** [comment] 2024-08-23 00:35
@SuperMaxusa but it also only has my DNS and IP as 0.0.0.0

**Comment by FunnyCorgi** [comment] 2024-08-23 00:47
![download](https://github.com/user-attachments/assets/911e5ba5-a522-45f3-88f0-eae3b60beeba)

**Comment by FunnyCorgi** [comment] 2024-08-23 00:52
@SuperMaxusa here is a screenshot:
![download](https://github.com/user-attachments/assets/51f405cd-3fc1-4bbc-af69-4791c7307c5b)

**Comment by SuperMaxusa** [comment] 2024-08-23 09:20
> What do I do if it isn't showing up in network connections as a connection

Try "Create a new connection" -> "Connect to the Internet" (or "Set up a home or small office network") -> "Set up my connection manually" -> "Connect using a broadband" "connection that is always on"

By default it should be created on startup, check if services "DNS Client", "DHCP Client" and "Network Connections" are running and have "Automatic" startup type (run `services.msc`)

**Comment by FunnyCorgi** [comment] 2024-08-23 11:08
Ok, I'll try that.

**Comment by FunnyCorgi** [comment] 2024-08-23 11:34
I just found out that all the mentioned services _dont start_ when using qemu _or_ v86. As soon as I started one, v86 showed in the column that network traffic was going on.

**Comment by FunnyCorgi** [comment] 2024-08-23 11:35
I just did `ipconfig /all`, and I had an IP address _and_ a DNS server!

**Comment by FunnyCorgi** [comment] 2024-08-23 11:35
I still am yet to try websites though. I will do it now.

**Comment by FunnyCorgi** [comment] 2024-08-23 13:54
Websites do work now!

**Comment by FunnyCorgi** [comment] 2024-08-23 13:56
@SuperMaxusa & @100tomer I believe that this issue can be closed now?
Also, @SuperMaxusa I would like help making a bat script or something which will start the DNS, Network Connections, and DHCP services.

**Comment by SuperMaxusa** [comment] 2024-08-23 14:21
> I would like help making a bat script or something which will start the DNS, Network Connections, and DHCP services, because they don't start on their own.

Hmm, did you set on all of them in right-click -> Properties -> Startup type: Automatic and these services are selected in `msconfig`? On https://smallvoid.com/articles/windows-xp/services/ mentioned the services that are enabled by default.

About bat script, you can run the services via [`net start`](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/start-stop-pause-resume-restart-sql-server-services?view=sql-server-ver16#dbDefault):
```batch
net start "Network Connections"
net start "DHCP Client"
net start "DNS Client"
ipconfig /release *
ipconfig /renew *
```

**Comment by FunnyCorgi** [comment] 2024-08-23 18:39
@SuperMaxusa I litterally just noticed just now that network connections service is set to manual oops =). I will try fixing that and see if it will fix the other services starting on their own, on it's own.

**Closed** 2024-08-24 18:46 UTC
