### ISSUE TITLE
restarting 98 takes forever

### ISSUE THREAD

**Issue by usernameisrobert** [copy/v86#1126] opened 2024-08-16 19:18 UTC
i was trying to connect to the internet, but when it came time to restart the PC for the settings to take effect, it just was stuck on the shutting down screen

and if thats because i cant use internet, then there is no reason to live

**Comment by ercan1104** [comment] 2024-08-17 16:51
> i was trying to connect to the internet, but when it came time to restart the PC for the settings to take effect, it just was stuck on the shutting down screen
> 
> and if thats because i cant use internet, then there is no reason to live

Have you used `networking.bat` from Desktop or you are using custom 98?

**Comment by copy** [comment] 2024-08-21 11:05
Duplicate of #234

**Closed by copy** 2024-08-21 11:05 UTC
