### ISSUE TITLE
Illegal instruction w/ Node.js (archlinux)

### ISSUE THREAD

**Issue by arcanis** [copy/v86#148] opened 2017-04-19 19:13 UTC
Running `node` in the archlinux image yields the following error: 

```
root@nyu:~# node
Illegal instruction
```

It makes it impossible to run v86 inside node inside v86 😄

**Comment by copy** [comment] 2017-04-19 19:33
Yep, duplicate of #48. You can grab an older release if you really want to run JavaScript on Linux in an emulator in a JavaScript engine in a browser in an operating system on real hardware.

**Closed by copy** 2017-04-19 19:33 UTC

**Comment by arcanis** [comment] 2019-04-20 06:10
Two years later I figured I should share my use case!

I work on Yarn, and I'd like to make a "tutorial" of some sort where users could run Yarn within their browsers. Could be useful to showcase some features, and also potentially to let people share reproduction of their bug reports (we get a lot of bug reports that we cannot act upon or even know whether they're still relevant).

I don't have the bandwidth to implement the missing instructions myself unfortunately (Yarn is already a huge commitment in itself), but if someone wonders whether that work would be useful, it definitely would for us ...
