### ISSUE TITLE
Getting Invalid argument with creating and manipulating files in 9p 

### ISSUE THREAD

**Issue by Darin755** [copy/v86#1154] opened 2024-09-12 16:34 UTC
So I recently created a new image for my project Browser Linux. However, in the new image the 9p filesystem does not seem to be working correctly. When ever a new file is created a Invalid argument error is generated. The file becomes a "ghost" file and is can not be read or deleted. This likely indicates something going wrong in the kernel as that error is triggered when the system call fails. However, I do not see any errors and mounting it with debug options does not do anything. 

The new image: (9p is mounted at /home)
https://darin755.github.io/browser-linux/src/?iso=rootfstesting.iso

I am not sure what is going wrong here.

**Comment by SuperMaxusa** [comment] 2024-09-12 17:56
#996, works for me on copy.sh/v86, maybe your version of v86 on Browser Linux is outdated?

![зображення](https://github.com/user-attachments/assets/e253495b-f9fe-435b-96d0-1353bad2e34e)

**Comment by Darin755** [comment] 2024-09-12 18:49
It is outdated but the new version causes a different issue.

**Comment by copy** [comment] 2024-09-12 19:14
Closing as duplicate of #996


> It is outdated but the new version causes a different issue.

This sort of comment is not very useful. What is the issue? Can you provide a testcase that allows me to reproduce locally? Can you run with debug.html or libv86-debug.js and paste the output here?

**Closed by copy** 2024-09-12 19:14 UTC

**Comment by Darin755** [comment] 2024-09-14 02:45
Yeah sorry about this issue. I made it while I was a little tired and looking back it isn't really useful.
