### ISSUE TITLE
Will There Be An Virtual x64

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [copy/v86#1009] opened 2024-04-10 10:39 UTC
Look hold on listen to me If You Did This You Would Get : 
- More People Testing Their OS's In `Virtual x86`
- Compatible With More Applications Such As Rocket League From Steam
- Compatible With x86 OS's 
- (I Wanted To Test My OSes In Virtualx86 But They Were x64)
- More ISO's Supported
- KDE And Gnome Desktop Enviorment Supported
- ChromiumOS
- And More

**Comment by copy** [comment] 2024-04-10 12:04
It would be nice, but it's also a big project.

Closing as duplicate of https://github.com/copy/v86/issues/133

**Closed by copy** 2024-04-10 12:04 UTC
