### ISSUE TITLE
Add OPFS/navigator.storage Support for Improved File System Integration

### ISSUE THREAD

**Issue by dkranke** [copy/v86#1053] opened 2024-05-27 00:27 UTC
**Description:**
Implement support for the [Origin Private File System (OPFS)](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system)/ navigator.storage to enhance file system integration in v86. This feature will allow direct file storage and retrieval in the browser, eliminating the need for custom 9p implementations for file transfer between the VM and the host.

**Justification:**
Integrating OPFS will simplify user interactions with the VM by leveraging native browser capabilities for file management, thus improving ease of use and performance.

**Implementation:**
* Evaluate direct OPFS integration versus a 9p protocol implementation using OPFS.
* Develop the necessary API hooks to support OPFS operations within the v86 environment.
* Ensure compatibility with existing file system operations and provide fallback options for browsers without OPFS support.

Benefits:
* Streamlined file transfer processes.
* Reduced complexity in VM file management.
* Enhanced performance and user experience.

**Comment by copy** [comment] 2024-05-28 11:39
From the linked page:

> Browsers persist the contents of the OPFS to disk somewhere, but you cannot expect to find the created files matched one-to-one. The OPFS is not intended to be visible to the user.

So this is not really useful for sharing files with the host.

Let's close this as a duplicate of https://github.com/copy/v86/issues/396

**Closed by copy** 2024-05-28 11:39 UTC
