### ISSUE TITLE
'Illegal instruction' when using GCC and floating point

### ISSUE THREAD

**Issue by gfwilliams** [copy/v86#94] opened 2016-03-30 15:09 UTC
Hi,

Floating point instructions seem to be supported in v86 (at least Python works), but it looks like something in GCC has problems with them...

I just tried compiling the following in http://copy.sh/v86/?profile=archlinux

```
int main() {
  return (int)3.141592;
}
```

Making it `3.141592f` didn't help either.

![v84_fp](https://cloud.githubusercontent.com/assets/754445/14146853/16c745b8-f691-11e5-818d-10d71eb4f940.png)

Amazing work though - I have an open source project for Microcontrollers that I'm trying to allow users to build inside the web browser (getting a build environment set up can be painful). With the recent speed improvements you've made it's tantalisingly close to being possible (~10 min build time).

**Comment by copy** [comment] 2016-03-30 21:10
`gcc` uses an SSE instruction, which is not yet implemented in the emulator. I'll close this as a dupe of #48.

> Amazing work though - I have an open source project for Microcontrollers that I'm trying to allow users to build inside the web browser (getting a build environment set up can be painful). With the recent speed improvements you've made it's tantalisingly close to being possible (~10 min build time).

Thanks. That's very cool. If you want to make this work, it should be possible to compile gcc without SSE on another machine (and the use that gcc in the vm to compile your application).

**Closed by copy** 2016-03-30 21:10 UTC

**Comment by gfwilliams** [comment] 2016-03-31 11:23
Great - thanks for the explanation!

I'll have a look - to be honest I might have to compile an ARM-GCC anyway, so doing it without SSE wouldn't be too painful.
