### ISSUE TITLE
initial_state

### ISSUE THREAD

**Issue by xming** [copy/v86#61] opened 2015-05-24 12:35 UTC
How does this work? When I add to the settings
```
        initial_state: {
            url: "./images/v86state.bin",
        },
```
I get 

```
Uncaught TypeError: Cannot read property 'za' of undefined
Ge	@	libv86.js:387
Ge	@	libv86.js:387
He	@	libv86.js:391
(anonymous function)	@	libv86.js:420
```

**Comment by xming** [comment] 2015-05-24 20:52
Somehow the save state from index.html wasn't usable but following the save_restore.html I can create working state files.

**Comment by copy** [comment] 2015-05-26 03:06
This shouldn't happen, I'll see what's going on here. Did you use the same settings (memory size and storage devices) in both cases?

**Comment by xming** [comment] 2015-05-26 08:38
Yes, I used same settings, will try to see if I can reproduce this.

**Comment by copy** [comment] 2015-08-22 12:57
I'll close this because I can't reproduce it anymore. It was probably a version mismatch.

Feel free to reopen if it happens again.

**Closed by copy** 2015-08-22 12:57 UTC
